### PR TITLE
try to fix CI

### PR DESCRIPTION
**Pull request by TomasTomecek**

### CODE REVIEW

**Review by jscotka — APPROVED** [review]
Thanks a lot for cleanup my changes.
Now automation just fails because of "python-dockerfile-prase"

**Comment by TomasTomecek** [comment]
Hm, I don't understand what's wrong.

**Comment by jscotka** [comment]
as we've discussed, @phracek used some new feature of  `python-dockerfile-prase`  in MTF. it caused regressions in most module lints and it waits for 
https://bodhi.fedoraproject.org/updates/FEDORA-2017-2bcc0e39df

This package should fix it because it installs packages from fedora-26 to conainer so this new version is still not there.

This is fault of MTF deployment process, when someone uses some new feature of some package what is not shipped in recent version of fedora -> leads to regressions in many testsuites.

**Comment by phracek** [comment]
I used from python-dockerfile-parse `fileobj=` but it is still in testing.

**Comment by TomasTomecek** [comment]
0.0.7 is installed (updates-testing is enabled)

```
python2-dockerfile-parse noarch 0.0.7-1.fc26             updates-testing  27 k
```

So... a bug in template repo or mtf? Can you reproduce locally?

**Comment by bkabrda** [comment]
Seems like we're hitting https://github.com/moby/moby/issues/9547

**Comment by bkabrda** [comment]
According to the comments in the referenced moby issue, it should be sufficient to run either `sleep 1` or `sync` in between the `chmod` command and the actual execution of `requirements.sh`. @TomasTomecek could you please try one of these?

**Comment by TomasTomecek** [comment]
-_- is that a joke?

**Comment by TomasTomecek** [comment]
The CI failures are now caused by https://github.com/fedora-modularity/meta-test-family/issues/142

**Comment by bkabrda** [comment]
I'm gonna go ahead and merge this, since it improves the current state and the CI is broken now anyway. Thanks!

**Pull request merged**
